name = "wedding-invitation"
compatibility_date = "2026-09-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "wedding-invitation-db"
database_id = "9576ce12-b44c-4d15-a116-d731ea1c29c6"
